"""init

Revision ID: e1f2c2675da2
Revises: 059fcd0d080b
Create Date: 2024-01-08 10:38:09.188973

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1f2c2675da2"
down_revision: Union[str, None] = "059fcd0d080b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person", sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_person_gender"), "person", ["gender"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_person_gender"), table_name="person")
    op.drop_column("person", "gender")
    # ### end Alembic commands ###
