/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j0VbVC89oHF
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function home() {
  return (
    <div className="flex flex-col min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
      <header className="flex items-center justify-between p-6 border-b dark:border-gray-800">
        <h1 className="text-2xl font-bold">Town & People Data</h1>
        <Button className="dark:border-gray-300" variant="outline">
          Refresh Data
        </Button>
      </header>
      <main className="flex-1 overflow-auto p-6">
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-4">Town Data</h2>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <Card>
              <CardContent className="space-y-2">
                <h3 className="text-lg font-semibold">Town Name</h3>
                <p className="text-gray-500 dark:text-gray-400">Population: 5000</p>
                <p className="text-gray-500 dark:text-gray-400">Location: 40.7128° N, 74.0060° W</p>
              </CardContent>
            </Card>
          </div>
        </section>
        <section>
          <h2 className="text-xl font-semibold mb-4">People Data</h2>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <Card>
              <CardContent className="space-y-2">
                <h3 className="text-lg font-semibold">Person Name</h3>
                <p className="text-gray-500 dark:text-gray-400">Age: 30</p>
                <p className="text-gray-500 dark:text-gray-400">Occupation: Developer</p>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="p-6 border-t dark:border-gray-800">
        <p className="text-center text-sm text-gray-500 dark:text-gray-400">
          © 2024 Town & People Data. All rights reserved.
        </p>
      </footer>
    </div>
  )
}
