"""added gender to people table

Revision ID: 19337525c1f2
Revises: 00266ad7263a
Create Date: 2024-01-08 00:47:59.867233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '19337525c1f2'
down_revision: Union[str, None] = '00266ad7263a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_person_gender'), 'person', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_gender'), table_name='person')
    op.drop_column('person', 'gender')
    # ### end Alembic commands ###
