name: Python Tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests      
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          pip install -r api/requirements.txt && python api/init_db.py
          pytest tests/test_towns.py 
